name: SweetTask
version: '${version}'
main: top.mrxiaom.sweet.taskplugin.SweetTask
api-version: 1.13
softdepend:
  - Vault
  - PlayerPoints
  - PlaceholderAPI
  - MythicMobs
  - CustomFishing
authors: [ MrXiaoM ]
folia-supported: true
libraries:
  - "org.jetbrains:annotations:24.0.0"
commands:
  sweettask:
    description: 'The main command of SweetTask'
    aliases: [ stask, task, st ]
